import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/organisms/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container mx-auto bg-slate-800 text-yellow-50">
        <Header />
        {children}
      </body>
    </html>
  );
}
